### PR TITLE
fix markdown link bug

### LINKED ISSUE #9: Linkify text with markdown links in it
I want to linkify text that might already have a markdown link (so just skip it) `[link](http://google.com)` but this is the output `[link]([http://google.com](http://google.com))`

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #9

### CODE REVIEW

**Comment by mxstbr** [comment]
Actually, now that I look at this it might be better to fix it in linkify itself?

**Comment by hipstersmoothie** [comment]
Likify itself doesn’t care about markdown though. This is what actually
creates markdown

**Comment by mxstbr** [comment]
Good point, works for me!

**Comment by hipstersmoothie** [comment]
Awsome! Can I expect a release today?

**Comment by mxstbr** [comment]
What's your npm username? I'll add you as an owner of the package so you can publish it

**Comment by hipstersmoothie** [comment]
`alisowski`

**Comment by mxstbr** [comment]
Done @hipstersmoothie

**Comment by hipstersmoothie** [comment]
published in v1.0.1

**Pull request merged**
